<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="KitchenMods">
      <HintPath>$(SteamPath)\common\PlateUp\PlateUp\PlateUp_Data\Managed\KitchenMods.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Kitchen.Common">
      <HintPath>$(SteamPath)\common\PlateUp\PlateUp\PlateUp_Data\Managed\Kitchen.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Kitchen.GameData">
      <HintPath>$(SteamPath)\common\PlateUp\PlateUp\PlateUp_Data\Managed\Kitchen.GameData.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.Entities">
      <HintPath>$(SteamPath)\common\PlateUp\PlateUp\PlateUp_Data\Managed\Unity.Entities.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>$(SteamPath)\common\PlateUp\PlateUp\PlateUp_Data\Managed\Unity.Collections.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(SteamPath)\common\PlateUp\PlateUp\PlateUp_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="KitchenLib-Workshop">
      <HintPath>$(SteamPath)\workshop\content\1599600\2898069883\KitchenLib-Workshop.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(SteamPath)\common\PlateUp\PlateUp\PlateUp_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Sirenix.Serialization">
      <HintPath>$(SteamPath)\common\PlateUp\PlateUp\PlateUp_Data\Managed\Sirenix.Serialization.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
